server:
  port: 9999
spring:
  application:
    name: cloud-gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
    gateway:
      discovery:
        locator:
          enabled: true #开启注册中心路由功能
#      routes:  # 路由
#        - id: cloud-demo-service #路由ID，没有固定要求，但是要保证唯一，建议配合服务名
#          # uri: http://localhost:9002 # 匹配提供服务的路由地址
#          uri: lb://cloud-demo-service
#          predicates: # 断言
#            - Path=/api/** # 断言，路径相匹配进行路由
